#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : php-timecop
Version  : 1.2.10
Release  : 1
URL      : https://pecl.php.net//get/timecop-1.2.10.tgz
Source0  : https://pecl.php.net//get/timecop-1.2.10.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: php-timecop-lib = %{version}-%{release}
BuildRequires : buildreq-php

%description
# php-timecop [![Travis CI build status](https://travis-ci.org/hnw/php-timecop.svg?branch=master)](https://travis-ci.org/hnw/php-timecop) [![CircleCI build status](https://circleci.com/gh/hnw/php-timecop.svg?style=shield)](https://circleci.com/gh/hnw/php-timecop) [![Wercker build status](https://app.wercker.com/status/bb9856dda9b2ced0bbfa44d50d7fc034/s/master "wercker status")](https://app.wercker.com/project/bykey/bb9856dda9b2ced0bbfa44d50d7fc034)[![Build status](https://ci.appveyor.com/api/projects/status/1q7c9bwera4cmv5g/branch/master?svg=true)](https://ci.appveyor.com/project/hnw/php-timecop/branch/master)

%package lib
Summary: lib components for the php-timecop package.
Group: Libraries

%description lib
lib components for the php-timecop package.


%prep
%setup -q -n timecop-1.2.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure
make  %{?_smp_mflags}

%install
%make_install


%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20180731/timecop.so
